{% set name = "pylev" %}
{% set version = "1.4.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/toastdriven/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f7bf8fb939af1457b301a0f16b3e8c3979031e36a852b7f58fa353a33b930780

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=42
    - wheel
  run:
    - python

test:
  source_files:
    - tests.py
  imports:
    - pylev
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - python -m unittest -v tests.py
  requires:
    - pip

about:
  home: https://github.com/toastdriven/pylev
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "A pure Python Levenshtein implementation that's not freaking GPL'd."
  description: "A pure Python Levenshtein implementation that's not freaking GPL'd. 
    Based off the Wikipedia code samples at http://en.wikipedia.org/wiki/Levenshtein_distance."
  doc_url: https://github.com/toastdriven/pylev
  dev_url: https://github.com/toastdriven/pylev

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
