travis:
  secure:
    BINSTAR_TOKEN: kJEU9Q/P7vGjMhS2ZS9OqVN9SlWLeBDw2+qS0Ne11GjMtLcirMVzTgVXUvQ4b3ZKzaQA43x2TSavhth1KmebqH7JfeHxqdVHR6Y3P78JFibXqGeXhLlBWdabWXrwe/20RPFtJAKdzWwLGVsg2hKJnf/d1fw18qP3FKCTnUMUwThJGxw3ARV6920DSbG2C7YDksV0IfMyknM11xB1MaBbr6+urg/i0OfzHkf9qESAGT+jRWVoXIi2iKQ0q/97Xh8b2VsDLLKO+KX+xTTaavI3gQKYEqQ70LU12gRQ8Xq8uqcgW0I40rESfkeR6g4YW2FF8trHKjV3KzkF8zG/SWdoqnMtcV8msUUYAJzG49MjTJQwLJw+pxvt6OZPx4CsqYAug6ChRRXU4vpt7qa3lDShWS62NnFVVfhw+921hni+ZxnbuXZDYBpTTtU4NsvWlly1dnKFBclzhOXXYQ44EL3sRMMEsHfr1ELJZXKnEFfQ43lZotVWq6yU7EHiAKQr051zhH7pQ12W+sjMrhUxvTXw1+g4u7t8sjsCr61L7A7/EqlI/9PDg5aIdkHFzKxGe4eSUxg2sOktzliIecOIp6AitZbxfZdFBccP/TbhW9Y++zH+ehciCBvMWFUwrbtJUI8jPuL6xvEGGJb5Ehz8YMHzudIb+oqeNBbqR3LsPdlLBGA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
